import 'package:freezed_annotation/freezed_annotation.dart';

import 'package:elajtech/features/admin/analytics/domain/entities/date_range.dart';

part 'admin_alert.freezed.dart';

/// تنبيه إداري — generated by the hourly checkAdminAlerts scheduled CF.
/// Deduplicated: one active alert per doctorId + AlertType combination.
@freezed
abstract class AdminAlert with _$AdminAlert {
  const factory AdminAlert({
    // ── required ───────────────────────────────────────────────────────────
    required String id,
    required AlertType type,
    required String doctorId,
    required String doctorName,
    required String title,
    required String message,

    /// القيمة التي أطلقت التنبيه (مثل: "5200 SAR"، "65%"، "12 يوماً")
    required String triggerValue,

    /// الحد المضبوط في admin_settings/alert_thresholds
    required String threshold,
    required DateTime createdAt,

    // ── optional / defaulted ───────────────────────────────────────────────
    @Default(false) bool isRead,
    DateTime? resolvedAt,
  }) = _AdminAlert;
}
