// Mocks generated by Mockito 5.4.6 from annotations
// in elajtech/test/widget/admin/admin_doctor_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i9;

import 'package:dartz/dartz.dart' as _i2;
import 'package:elajtech/core/error/failures.dart' as _i5;
import 'package:elajtech/core/services/storage_service.dart' as _i8;
import 'package:elajtech/features/admin/domain/entities/audit_log.dart' as _i7;
import 'package:elajtech/features/admin/domain/repositories/admin_repository.dart'
    as _i3;
import 'package:elajtech/shared/models/user_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AdminRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminRepository extends _i1.Mock implements _i3.AdminRepository {
  MockAdminRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserModel>>> getAllDoctors() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDoctors, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.UserModel>>(
                    this,
                    Invocation.method(#getAllDoctors, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserModel>>> getAllPatients() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPatients, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.UserModel>>(
                    this,
                    Invocation.method(#getAllPatients, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> createDoctor({
    required _i6.UserModel? doctor,
    required String? password,
    required String? adminId,
    required String? adminName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDoctor, [], {
              #doctor: doctor,
              #password: password,
              #adminId: adminId,
              #adminName: adminName,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#createDoctor, [], {
                  #doctor: doctor,
                  #password: password,
                  #adminId: adminId,
                  #adminName: adminName,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> updateDoctorProfile({
    required _i6.UserModel? updatedDoctor,
    required _i6.UserModel? previousDoctor,
    required String? adminId,
    required String? adminName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDoctorProfile, [], {
              #updatedDoctor: updatedDoctor,
              #previousDoctor: previousDoctor,
              #adminId: adminId,
              #adminName: adminName,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#updateDoctorProfile, [], {
                  #updatedDoctor: updatedDoctor,
                  #previousDoctor: previousDoctor,
                  #adminId: adminId,
                  #adminName: adminName,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> setAccountStatus({
    required String? targetUserId,
    required bool? isActive,
    required String? adminId,
    required String? adminName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setAccountStatus, [], {
              #targetUserId: targetUserId,
              #isActive: isActive,
              #adminId: adminId,
              #adminName: adminName,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#setAccountStatus, [], {
                  #targetUserId: targetUserId,
                  #isActive: isActive,
                  #adminId: adminId,
                  #adminName: adminName,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
  getPatientEmrHistory(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#getPatientEmrHistory, [patientId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<Map<String, dynamic>>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#getPatientEmrHistory, [patientId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Stream<List<_i7.AuditLog>> watchAuditLogs() =>
      (super.noSuchMethod(
            Invocation.method(#watchAuditLogs, []),
            returnValue: _i4.Stream<List<_i7.AuditLog>>.empty(),
          )
          as _i4.Stream<List<_i7.AuditLog>>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i8.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> uploadProfileImage(_i9.File? file, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [file, userId]),
            returnValue: _i4.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileImage, [file, userId]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> deleteProfileImage(String? imageUrl) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfileImage, [imageUrl]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
