// Mocks generated by Mockito 5.4.6 from annotations
// in elajtech/test/unit/services/agora_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:elajtech/core/models/call_log_model.dart' as _i6;
import 'package:elajtech/core/models/device_info_model.dart' as _i5;
import 'package:elajtech/core/services/call_monitoring_service.dart' as _i3;
import 'package:elajtech/core/services/device_info_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDeviceInfoService_0 extends _i1.SmartFake
    implements _i2.DeviceInfoService {
  _FakeDeviceInfoService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CallMonitoringService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallMonitoringService extends _i1.Mock
    implements _i3.CallMonitoringService {
  MockCallMonitoringService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceInfoService get deviceInfoService =>
      (super.noSuchMethod(
            Invocation.getter(#deviceInfoService),
            returnValue: _FakeDeviceInfoService_0(
              this,
              Invocation.getter(#deviceInfoService),
            ),
          )
          as _i2.DeviceInfoService);

  @override
  set deviceInfoService(_i2.DeviceInfoService? value) => super.noSuchMethod(
    Invocation.setter(#deviceInfoService, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> logCallAttempt({
    required String? appointmentId,
    required String? userId,
    _i5.DeviceInfoModel? deviceInfo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logCallAttempt, [], {
              #appointmentId: appointmentId,
              #userId: userId,
              #deviceInfo: deviceInfo,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logCallSuccess({
    required String? appointmentId,
    required String? userId,
    required String? channelName,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logCallSuccess, [], {
              #appointmentId: appointmentId,
              #userId: userId,
              #channelName: channelName,
              #metadata: metadata,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logCallError({
    required String? appointmentId,
    required String? userId,
    required String? errorType,
    required String? errorMessage,
    String? stackTrace,
    _i5.DeviceInfoModel? deviceInfo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logCallError, [], {
              #appointmentId: appointmentId,
              #userId: userId,
              #errorType: errorType,
              #errorMessage: errorMessage,
              #stackTrace: stackTrace,
              #deviceInfo: deviceInfo,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logConnectionFailure({
    required String? appointmentId,
    required String? userId,
    required String? reason,
    _i5.DeviceInfoModel? deviceInfo,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logConnectionFailure, [], {
              #appointmentId: appointmentId,
              #userId: userId,
              #reason: reason,
              #deviceInfo: deviceInfo,
              #metadata: metadata,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logMediaDeviceError({
    required String? appointmentId,
    required String? userId,
    required String? deviceType,
    required String? errorMessage,
    _i5.DeviceInfoModel? deviceInfo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logMediaDeviceError, [], {
              #appointmentId: appointmentId,
              #userId: userId,
              #deviceType: deviceType,
              #errorMessage: errorMessage,
              #deviceInfo: deviceInfo,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logCallEnded({
    required String? appointmentId,
    required String? userId,
    int? duration,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logCallEnded, [], {
              #appointmentId: appointmentId,
              #userId: userId,
              #duration: duration,
              #metadata: metadata,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.CallLogModel>> getLogsForAppointment(
    String? appointmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLogsForAppointment, [appointmentId]),
            returnValue: _i4.Future<List<_i6.CallLogModel>>.value(
              <_i6.CallLogModel>[],
            ),
          )
          as _i4.Future<List<_i6.CallLogModel>>);

  @override
  _i4.Future<List<_i6.CallLogModel>> getLogsForUser(
    String? userId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLogsForUser, [userId], {#limit: limit}),
            returnValue: _i4.Future<List<_i6.CallLogModel>>.value(
              <_i6.CallLogModel>[],
            ),
          )
          as _i4.Future<List<_i6.CallLogModel>>);

  @override
  _i4.Future<List<_i6.CallLogModel>> getErrorLogs({int? limit = 100}) =>
      (super.noSuchMethod(
            Invocation.method(#getErrorLogs, [], {#limit: limit}),
            returnValue: _i4.Future<List<_i6.CallLogModel>>.value(
              <_i6.CallLogModel>[],
            ),
          )
          as _i4.Future<List<_i6.CallLogModel>>);
}
