// Mocks generated by Mockito 5.4.6 from annotations
// in elajtech/test/unit/features/packages/domain/get_patient_packages_for_admin_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:elajtech/core/error/failures.dart' as _i6;
import 'package:elajtech/features/packages/domain/entities/patient_package_entity.dart'
    as _i7;
import 'package:elajtech/features/packages/domain/repositories/patient_package_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_1<T1 extends Object?> extends _i1.SmartFake
    implements _i3.DocumentReference<T1> {
  _FakeDocumentReference_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSnapshotMetadata_2 extends _i1.SmartFake
    implements _i3.SnapshotMetadata {
  _FakeSnapshotMetadata_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PatientPackageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPatientPackageRepository extends _i1.Mock
    implements _i4.PatientPackageRepository {
  MockPatientPackageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.PatientPackageEntity>>>
  getPatientPackages({required String? patientId}) =>
      (super.noSuchMethod(
            Invocation.method(#getPatientPackages, [], {#patientId: patientId}),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i7.PatientPackageEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i7.PatientPackageEntity>>(
                    this,
                    Invocation.method(#getPatientPackages, [], {
                      #patientId: patientId,
                    }),
                  ),
                ),
          )
          as _i5.Future<
            _i2.Either<_i6.Failure, List<_i7.PatientPackageEntity>>
          >);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.PatientPackageEntity>>
  getPatientPackageByIdForPatient({
    required String? patientId,
    required String? patientPackageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPatientPackageByIdForPatient, [], {
              #patientId: patientId,
              #patientPackageId: patientPackageId,
            }),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i7.PatientPackageEntity>
                >.value(
                  _FakeEither_0<_i6.Failure, _i7.PatientPackageEntity>(
                    this,
                    Invocation.method(#getPatientPackageByIdForPatient, [], {
                      #patientId: patientId,
                      #patientPackageId: patientPackageId,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.PatientPackageEntity>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.PatientPackageEntity>>
  getPatientPackageByIdForAdmin({
    required String? patientId,
    required String? patientPackageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPatientPackageByIdForAdmin, [], {
              #patientId: patientId,
              #patientPackageId: patientPackageId,
            }),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i7.PatientPackageEntity>
                >.value(
                  _FakeEither_0<_i6.Failure, _i7.PatientPackageEntity>(
                    this,
                    Invocation.method(#getPatientPackageByIdForAdmin, [], {
                      #patientId: patientId,
                      #patientPackageId: patientPackageId,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.PatientPackageEntity>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.PatientPackageEntity?>>
  findActiveOrPendingByPackageId({
    required String? patientId,
    required String? packageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findActiveOrPendingByPackageId, [], {
              #patientId: patientId,
              #packageId: packageId,
            }),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i7.PatientPackageEntity?>
                >.value(
                  _FakeEither_0<_i6.Failure, _i7.PatientPackageEntity?>(
                    this,
                    Invocation.method(#findActiveOrPendingByPackageId, [], {
                      #patientId: patientId,
                      #packageId: packageId,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.PatientPackageEntity?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> createPatientPackage({
    required String? patientId,
    required String? packageId,
    required String? clinicId,
    required _i7.PatientPackageStatus? status,
    required DateTime? purchaseDate,
    required DateTime? expiryDate,
    required int? totalServicesCount,
    required List<String>? servicesUsageInit,
    required String? paymentTransactionId,
    required String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPatientPackage, [], {
              #patientId: patientId,
              #packageId: packageId,
              #clinicId: clinicId,
              #status: status,
              #purchaseDate: purchaseDate,
              #expiryDate: expiryDate,
              #totalServicesCount: totalServicesCount,
              #servicesUsageInit: servicesUsageInit,
              #paymentTransactionId: paymentTransactionId,
              #category: category,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#createPatientPackage, [], {
                  #patientId: patientId,
                  #packageId: packageId,
                  #clinicId: clinicId,
                  #status: status,
                  #purchaseDate: purchaseDate,
                  #expiryDate: expiryDate,
                  #totalServicesCount: totalServicesCount,
                  #servicesUsageInit: servicesUsageInit,
                  #paymentTransactionId: paymentTransactionId,
                  #category: category,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.PatientPackageEntity>>>
  listPatientPackagesForAdmin({
    required String? patientId,
    _i3.DocumentSnapshot<Object?>? lastDocument,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listPatientPackagesForAdmin, [], {
              #patientId: patientId,
              #lastDocument: lastDocument,
              #limit: limit,
            }),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i7.PatientPackageEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i7.PatientPackageEntity>>(
                    this,
                    Invocation.method(#listPatientPackagesForAdmin, [], {
                      #patientId: patientId,
                      #lastDocument: lastDocument,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<
            _i2.Either<_i6.Failure, List<_i7.PatientPackageEntity>>
          >);
}

/// A class which mocks [DocumentSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentSnapshot<T extends Object?> extends _i1.Mock
    implements _i3.DocumentSnapshot<T> {
  MockDocumentSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i3.DocumentReference<T> get reference =>
      (super.noSuchMethod(
            Invocation.getter(#reference),
            returnValue: _FakeDocumentReference_1<T>(
              this,
              Invocation.getter(#reference),
            ),
          )
          as _i3.DocumentReference<T>);

  @override
  _i3.SnapshotMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeSnapshotMetadata_2(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i3.SnapshotMetadata);

  @override
  bool get exists =>
      (super.noSuchMethod(Invocation.getter(#exists), returnValue: false)
          as bool);

  @override
  dynamic get(Object? field) =>
      super.noSuchMethod(Invocation.method(#get, [field]));

  @override
  dynamic operator [](Object? field) =>
      super.noSuchMethod(Invocation.method(#[], [field]));
}
