// Mocks generated by Mockito 5.4.6 from annotations
// in elajtech/test/unit/features/packages/domain/update_clinic_package_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i7;
import 'package:dartz/dartz.dart' as _i2;
import 'package:elajtech/core/error/failures.dart' as _i5;
import 'package:elajtech/features/packages/domain/entities/package_entity.dart'
    as _i6;
import 'package:elajtech/features/packages/domain/repositories/package_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PackageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPackageRepository extends _i1.Mock implements _i3.PackageRepository {
  MockPackageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PackageEntity>>>
  listCategoryPackages({
    required String? clinicId,
    required _i6.PackageCategory? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listCategoryPackages, [], {
              #clinicId: clinicId,
              #category: category,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PackageEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PackageEntity>>(
                    this,
                    Invocation.method(#listCategoryPackages, [], {
                      #clinicId: clinicId,
                      #category: category,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PackageEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PackageEntity>>>
  listClinicPackagesForAdmin({
    required String? clinicId,
    _i7.DocumentSnapshot<Object?>? lastDocument,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listClinicPackagesForAdmin, [], {
              #clinicId: clinicId,
              #lastDocument: lastDocument,
              #limit: limit,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PackageEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PackageEntity>>(
                    this,
                    Invocation.method(#listClinicPackagesForAdmin, [], {
                      #clinicId: clinicId,
                      #lastDocument: lastDocument,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PackageEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PackageEntity>> getPackageById({
    required String? clinicId,
    required String? packageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPackageById, [], {
              #clinicId: clinicId,
              #packageId: packageId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.PackageEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.PackageEntity>(
                    this,
                    Invocation.method(#getPackageById, [], {
                      #clinicId: clinicId,
                      #packageId: packageId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PackageEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> createPackage(
    _i6.PackageEntity? package,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPackage, [package]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#createPackage, [package]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> updatePackage(
    _i6.PackageEntity? package,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePackage, [package]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#updatePackage, [package]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> updatePackageStatus({
    required String? clinicId,
    required String? packageId,
    required _i6.PackageStatus? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePackageStatus, [], {
              #clinicId: clinicId,
              #packageId: packageId,
              #status: status,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#updatePackageStatus, [], {
                  #clinicId: clinicId,
                  #packageId: packageId,
                  #status: status,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
