// Mocks generated by Mockito 5.4.6 from annotations
// in elajtech/test/unit/features/packages/domain/upload_package_document_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:elajtech/core/error/failures.dart' as _i5;
import 'package:elajtech/features/notifications/domain/repositories/notification_repository.dart'
    as _i7;
import 'package:elajtech/features/packages/domain/entities/package_document_entity.dart'
    as _i6;
import 'package:elajtech/features/packages/domain/repositories/package_document_repository.dart'
    as _i3;
import 'package:elajtech/shared/models/notification_model.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PackageDocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPackageDocumentRepository extends _i1.Mock
    implements _i3.PackageDocumentRepository {
  MockPackageDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PackageDocumentEntity>>>
  getDocumentsByPatientPackage({
    required String? patientId,
    required String? patientPackageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDocumentsByPatientPackage, [], {
              #patientId: patientId,
              #patientPackageId: patientPackageId,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PackageDocumentEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PackageDocumentEntity>>(
                    this,
                    Invocation.method(#getDocumentsByPatientPackage, [], {
                      #patientId: patientId,
                      #patientPackageId: patientPackageId,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, List<_i6.PackageDocumentEntity>>
          >);

  @override
  _i4.Stream<List<_i6.PackageDocumentEntity>> streamDocumentsByPatientPackage({
    required String? patientId,
    required String? patientPackageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamDocumentsByPatientPackage, [], {
              #patientId: patientId,
              #patientPackageId: patientPackageId,
            }),
            returnValue: _i4.Stream<List<_i6.PackageDocumentEntity>>.empty(),
          )
          as _i4.Stream<List<_i6.PackageDocumentEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PackageDocumentEntity>>
  uploadDocument({
    required String? localFilePath,
    required String? patientId,
    required String? patientPackageId,
    required String? packageId,
    required String? clinicId,
    required _i6.DocumentType? documentType,
    required String? title,
    required String? uploadedByUserId,
    required String? uploadedByRole,
    String? serviceId,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDocument, [], {
              #localFilePath: localFilePath,
              #patientId: patientId,
              #patientPackageId: patientPackageId,
              #packageId: packageId,
              #clinicId: clinicId,
              #documentType: documentType,
              #title: title,
              #uploadedByUserId: uploadedByUserId,
              #uploadedByRole: uploadedByRole,
              #serviceId: serviceId,
              #description: description,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.PackageDocumentEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.PackageDocumentEntity>(
                    this,
                    Invocation.method(#uploadDocument, [], {
                      #localFilePath: localFilePath,
                      #patientId: patientId,
                      #patientPackageId: patientPackageId,
                      #packageId: packageId,
                      #clinicId: clinicId,
                      #documentType: documentType,
                      #title: title,
                      #uploadedByUserId: uploadedByUserId,
                      #uploadedByRole: uploadedByRole,
                      #serviceId: serviceId,
                      #description: description,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PackageDocumentEntity>>);
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i7.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> saveNotification(
    _i8.NotificationModel? notification,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveNotification, [notification]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#saveNotification, [notification]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.NotificationModel>>>
  getNotificationsForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationsForUser, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i8.NotificationModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i8.NotificationModel>>(
                    this,
                    Invocation.method(#getNotificationsForUser, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.NotificationModel>>>);

  @override
  _i4.Stream<List<_i8.NotificationModel>> getNotificationsStream(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationsStream, [userId]),
            returnValue: _i4.Stream<List<_i8.NotificationModel>>.empty(),
          )
          as _i4.Stream<List<_i8.NotificationModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> markAllNotificationsAsRead(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markAllNotificationsAsRead, [userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#markAllNotificationsAsRead, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
