// Mocks generated by Mockito 5.4.6 from annotations
// in elajtech/test/widget/features/admin/presentation/screens/admin_patient_package_context_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:elajtech/features/packages/domain/entities/package_document_entity.dart'
    as _i5;
import 'package:elajtech/features/packages/presentation/providers/admin_patient_packages_provider.dart'
    as _i3;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAsyncValue_1<T> extends _i1.SmartFake implements _i2.AsyncValue<T> {
  _FakeAsyncValue_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AdminPatientPackageWriteNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminPatientPackageWriteNotifier extends _i1.Mock
    implements _i3.AdminPatientPackageWriteNotifier {
  @override
  _i2.NotifierProviderRef<_i2.AsyncValue<void>> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeNotifierProviderRef_0<_i2.AsyncValue<void>>(
              this,
              Invocation.getter(#ref),
            ),
            returnValueForMissingStub:
                _FakeNotifierProviderRef_0<_i2.AsyncValue<void>>(
                  this,
                  Invocation.getter(#ref),
                ),
          )
          as _i2.NotifierProviderRef<_i2.AsyncValue<void>>);

  @override
  _i2.AsyncValue<void> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAsyncValue_1<void>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeAsyncValue_1<void>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.AsyncValue<void>);

  @override
  set state(_i2.AsyncValue<void>? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.AsyncValue<void> build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _FakeAsyncValue_1<void>(
              this,
              Invocation.method(#build, []),
            ),
            returnValueForMissingStub: _FakeAsyncValue_1<void>(
              this,
              Invocation.method(#build, []),
            ),
          )
          as _i2.AsyncValue<void>);

  @override
  _i4.Future<bool> uploadDocument({
    required String? localFilePath,
    required String? patientId,
    required String? patientPackageId,
    required String? packageId,
    required String? clinicId,
    required _i5.DocumentType? documentType,
    required String? title,
    required String? uploadedByUserId,
    required String? uploadedByRole,
    String? serviceId,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDocument, [], {
              #localFilePath: localFilePath,
              #patientId: patientId,
              #patientPackageId: patientPackageId,
              #packageId: packageId,
              #clinicId: clinicId,
              #documentType: documentType,
              #title: title,
              #uploadedByUserId: uploadedByUserId,
              #uploadedByRole: uploadedByRole,
              #serviceId: serviceId,
              #description: description,
            }),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateServiceUsage({
    required String? patientId,
    required String? patientPackageId,
    required String? serviceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateServiceUsage, [], {
              #patientId: patientId,
              #patientPackageId: patientPackageId,
              #serviceId: serviceId,
            }),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateNotes({
    required String? patientId,
    required String? patientPackageId,
    required String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotes, [], {
              #patientId: patientId,
              #patientPackageId: patientPackageId,
              #notes: notes,
            }),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void listenSelf(
    void Function(_i2.AsyncValue<void>?, _i2.AsyncValue<void>)? listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<void>? previous,
    _i2.AsyncValue<void>? next,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
