// Mocks generated by Mockito 5.4.6 from annotations
// in elajtech/test/unit/providers/appointments_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:elajtech/core/error/failures.dart' as _i5;
import 'package:elajtech/features/appointments/domain/repositories/appointment_repository.dart'
    as _i3;
import 'package:elajtech/features/notifications/domain/repositories/notification_repository.dart'
    as _i7;
import 'package:elajtech/shared/models/appointment_model.dart' as _i6;
import 'package:elajtech/shared/models/notification_model.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppointmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppointmentRepository extends _i1.Mock
    implements _i3.AppointmentRepository {
  MockAppointmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> saveAppointment(
    _i6.AppointmentModel? appointment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveAppointment, [appointment]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#saveAppointment, [appointment]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> bookAppointment(
    _i6.AppointmentModel? appointment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bookAppointment, [appointment]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#bookAppointment, [appointment]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AppointmentModel>>>
  getAppointmentsForPatient(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentsForPatient, [patientId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.AppointmentModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.AppointmentModel>>(
                    this,
                    Invocation.method(#getAppointmentsForPatient, [patientId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AppointmentModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AppointmentModel>>>
  getAppointmentsForDoctor(String? doctorId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentsForDoctor, [doctorId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.AppointmentModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.AppointmentModel>>(
                    this,
                    Invocation.method(#getAppointmentsForDoctor, [doctorId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AppointmentModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> checkAppointmentConflict({
    required String? patientId,
    required _i6.AppointmentModel? newAppointment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkAppointmentConflict, [], {
              #patientId: patientId,
              #newAppointment: newAppointment,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#checkAppointmentConflict, [], {
                  #patientId: patientId,
                  #newAppointment: newAppointment,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AppointmentModel>>>
  getActiveAppointmentsForPatient(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveAppointmentsForPatient, [patientId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.AppointmentModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.AppointmentModel>>(
                    this,
                    Invocation.method(#getActiveAppointmentsForPatient, [
                      patientId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AppointmentModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AppointmentModel>>>
  getActiveAppointmentsForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveAppointmentsForDate, [date]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.AppointmentModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.AppointmentModel>>(
                    this,
                    Invocation.method(#getActiveAppointmentsForDate, [date]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AppointmentModel>>>);
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i7.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> saveNotification(
    _i8.NotificationModel? notification,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveNotification, [notification]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#saveNotification, [notification]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.NotificationModel>>>
  getNotificationsForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationsForUser, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i8.NotificationModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i8.NotificationModel>>(
                    this,
                    Invocation.method(#getNotificationsForUser, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.NotificationModel>>>);

  @override
  _i4.Stream<List<_i8.NotificationModel>> getNotificationsStream(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationsStream, [userId]),
            returnValue: _i4.Stream<List<_i8.NotificationModel>>.empty(),
          )
          as _i4.Stream<List<_i8.NotificationModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> markAllNotificationsAsRead(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markAllNotificationsAsRead, [userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#markAllNotificationsAsRead, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
