// Mocks generated by Mockito 5.4.6 from annotations
// in elajtech/test/unit/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:elajtech/core/error/failures.dart' as _i6;
import 'package:elajtech/features/auth/domain/models/phone_verification_data.dart'
    as _i7;
import 'package:elajtech/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:elajtech/shared/models/user_model.dart' as _i8;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i5.User?>.empty(),
          )
          as _i4.Stream<_i5.User?>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i7.PhoneVerificationData>>
  verifyPhoneNumber({required String? phoneNumber}) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneNumber, [], {
              #phoneNumber: phoneNumber,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i6.Failure, _i7.PhoneVerificationData>
                >.value(
                  _FakeEither_0<_i6.Failure, _i7.PhoneVerificationData>(
                    this,
                    Invocation.method(#verifyPhoneNumber, [], {
                      #phoneNumber: phoneNumber,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i7.PhoneVerificationData>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>> signInWithPhoneNumber({
    required String? verificationId,
    required String? smsCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhoneNumber, [], {
              #verificationId: verificationId,
              #smsCode: smsCode,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>>.value(
                  _FakeEither_0<_i6.Failure, _i8.UserModel>(
                    this,
                    Invocation.method(#signInWithPhoneNumber, [], {
                      #verificationId: verificationId,
                      #smsCode: smsCode,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>> signUp({
    required String? email,
    required String? password,
    required String? fullName,
    required _i8.UserType? userType,
    String? phoneNumber,
    String? licenseNumber,
    List<String>? specializations,
    String? clinicName,
    String? clinicAddress,
    List<String>? consultationTypes,
    String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #fullName: fullName,
              #userType: userType,
              #phoneNumber: phoneNumber,
              #licenseNumber: licenseNumber,
              #specializations: specializations,
              #clinicName: clinicName,
              #clinicAddress: clinicAddress,
              #consultationTypes: consultationTypes,
              #username: username,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>>.value(
                  _FakeEither_0<_i6.Failure, _i8.UserModel>(
                    this,
                    Invocation.method(#signUp, [], {
                      #email: email,
                      #password: password,
                      #fullName: fullName,
                      #userType: userType,
                      #phoneNumber: phoneNumber,
                      #licenseNumber: licenseNumber,
                      #specializations: specializations,
                      #clinicName: clinicName,
                      #clinicAddress: clinicAddress,
                      #consultationTypes: consultationTypes,
                      #username: username,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>>.value(
                  _FakeEither_0<_i6.Failure, _i8.UserModel>(
                    this,
                    Invocation.method(#signIn, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i6.Failure, _i2.Unit>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>>.value(
                  _FakeEither_0<_i6.Failure, _i8.UserModel>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i6.Failure, _i2.Unit>(
                this,
                Invocation.method(#resetPassword, [email]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i6.Failure, _i2.Unit>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> updateUser(
    _i8.UserModel? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i6.Failure, _i2.Unit>(
                this,
                Invocation.method(#updateUser, [user]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> changePassword(
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [newPassword]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i6.Failure, _i2.Unit>(
                this,
                Invocation.method(#changePassword, [newPassword]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i7.PhoneVerificationData>>
  verifyPhoneNumberForLinking({required String? phoneNumber}) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneNumberForLinking, [], {
              #phoneNumber: phoneNumber,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i6.Failure, _i7.PhoneVerificationData>
                >.value(
                  _FakeEither_0<_i6.Failure, _i7.PhoneVerificationData>(
                    this,
                    Invocation.method(#verifyPhoneNumberForLinking, [], {
                      #phoneNumber: phoneNumber,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i7.PhoneVerificationData>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>> linkPhoneToCurrentUser({
    required String? verificationId,
    required String? smsCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkPhoneToCurrentUser, [], {
              #verificationId: verificationId,
              #smsCode: smsCode,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>>.value(
                  _FakeEither_0<_i6.Failure, _i8.UserModel>(
                    this,
                    Invocation.method(#linkPhoneToCurrentUser, [], {
                      #verificationId: verificationId,
                      #smsCode: smsCode,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, String>> startSignUpWithEmailAndPhone({
    required String? email,
    required String? password,
    required String? fullName,
    required String? phoneNumber,
    String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startSignUpWithEmailAndPhone, [], {
              #email: email,
              #password: password,
              #fullName: fullName,
              #phoneNumber: phoneNumber,
              #username: username,
            }),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#startSignUpWithEmailAndPhone, [], {
                  #email: email,
                  #password: password,
                  #fullName: fullName,
                  #phoneNumber: phoneNumber,
                  #username: username,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>>
  confirmSignUpAndCreateProfile({
    required String? verificationId,
    required String? smsCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmSignUpAndCreateProfile, [], {
              #verificationId: verificationId,
              #smsCode: smsCode,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>>.value(
                  _FakeEither_0<_i6.Failure, _i8.UserModel>(
                    this,
                    Invocation.method(#confirmSignUpAndCreateProfile, [], {
                      #verificationId: verificationId,
                      #smsCode: smsCode,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i8.UserModel>>);
}
