// Mocks generated by Mockito 5.4.6 from annotations
// in elajtech/test/integration/packages_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i8;
import 'package:dartz/dartz.dart' as _i2;
import 'package:elajtech/core/error/failures.dart' as _i5;
import 'package:elajtech/features/packages/domain/entities/package_service_item.dart'
    as _i7;
import 'package:elajtech/features/packages/domain/entities/patient_package_entity.dart'
    as _i6;
import 'package:elajtech/features/packages/domain/repositories/patient_package_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PatientPackageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPatientPackageRepository extends _i1.Mock
    implements _i3.PatientPackageRepository {
  MockPatientPackageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PatientPackageEntity>>>
  getPatientPackages({required String? patientId}) =>
      (super.noSuchMethod(
            Invocation.method(#getPatientPackages, [], {#patientId: patientId}),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PatientPackageEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PatientPackageEntity>>(
                    this,
                    Invocation.method(#getPatientPackages, [], {
                      #patientId: patientId,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, List<_i6.PatientPackageEntity>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PatientPackageEntity>>
  getPatientPackageByIdForPatient({
    required String? patientId,
    required String? patientPackageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPatientPackageByIdForPatient, [], {
              #patientId: patientId,
              #patientPackageId: patientPackageId,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.PatientPackageEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.PatientPackageEntity>(
                    this,
                    Invocation.method(#getPatientPackageByIdForPatient, [], {
                      #patientId: patientId,
                      #patientPackageId: patientPackageId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PatientPackageEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PatientPackageEntity>>
  getPatientPackageByIdForAdmin({
    required String? patientId,
    required String? patientPackageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPatientPackageByIdForAdmin, [], {
              #patientId: patientId,
              #patientPackageId: patientPackageId,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.PatientPackageEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.PatientPackageEntity>(
                    this,
                    Invocation.method(#getPatientPackageByIdForAdmin, [], {
                      #patientId: patientId,
                      #patientPackageId: patientPackageId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PatientPackageEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PatientPackageEntity?>>
  findActiveOrPendingByPackageId({
    required String? patientId,
    required String? packageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findActiveOrPendingByPackageId, [], {
              #patientId: patientId,
              #packageId: packageId,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.PatientPackageEntity?>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.PatientPackageEntity?>(
                    this,
                    Invocation.method(#findActiveOrPendingByPackageId, [], {
                      #patientId: patientId,
                      #packageId: packageId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PatientPackageEntity?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> createPatientPackage({
    required String? patientId,
    required String? packageId,
    required String? packageName,
    required String? clinicId,
    required _i6.PatientPackageStatus? status,
    required DateTime? purchaseDate,
    required DateTime? expiryDate,
    required int? totalServicesCount,
    required List<String>? servicesUsageInit,
    required List<_i7.PackageServiceItem>? packageServices,
    required String? paymentTransactionId,
    required String? category,
    required bool? isTestPurchase,
    required String? description,
    required String? shortDescription,
    required int? validityDays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPatientPackage, [], {
              #patientId: patientId,
              #packageId: packageId,
              #packageName: packageName,
              #clinicId: clinicId,
              #status: status,
              #purchaseDate: purchaseDate,
              #expiryDate: expiryDate,
              #totalServicesCount: totalServicesCount,
              #servicesUsageInit: servicesUsageInit,
              #packageServices: packageServices,
              #paymentTransactionId: paymentTransactionId,
              #category: category,
              #isTestPurchase: isTestPurchase,
              #description: description,
              #shortDescription: shortDescription,
              #validityDays: validityDays,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#createPatientPackage, [], {
                  #patientId: patientId,
                  #packageId: packageId,
                  #packageName: packageName,
                  #clinicId: clinicId,
                  #status: status,
                  #purchaseDate: purchaseDate,
                  #expiryDate: expiryDate,
                  #totalServicesCount: totalServicesCount,
                  #servicesUsageInit: servicesUsageInit,
                  #packageServices: packageServices,
                  #paymentTransactionId: paymentTransactionId,
                  #category: category,
                  #isTestPurchase: isTestPurchase,
                  #description: description,
                  #shortDescription: shortDescription,
                  #validityDays: validityDays,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PatientPackageEntity>>>
  listPatientPackagesForAdmin({
    required String? patientId,
    _i8.DocumentSnapshot<Object?>? lastDocument,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listPatientPackagesForAdmin, [], {
              #patientId: patientId,
              #lastDocument: lastDocument,
              #limit: limit,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PatientPackageEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PatientPackageEntity>>(
                    this,
                    Invocation.method(#listPatientPackagesForAdmin, [], {
                      #patientId: patientId,
                      #lastDocument: lastDocument,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, List<_i6.PatientPackageEntity>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateNotes({
    required String? patientId,
    required String? patientPackageId,
    required String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotes, [], {
              #patientId: patientId,
              #patientPackageId: patientPackageId,
              #notes: notes,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateNotes, [], {
                  #patientId: patientId,
                  #patientPackageId: patientPackageId,
                  #notes: notes,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
